using System.IO;
using FecSubmitter.Models;
using FecWebService;
using System.Text.Json;
using System.Threading.Tasks;

namespace FecSubmitter
{
	internal class FecSubmissionService
	{
		public static async Task SubmitFecFile(string fecFilePath)
		{
			var webService = new UploadServiceClient();

			var arg0 = GetFecSubmissionDetails();
			var arg1 = await File.ReadAllBytesAsync(fecFilePath);

			// For small .fec files, the transfer will succeed but the response cannot be understood by the boilerplate web service code generated by Visual Studio.
			// Root cause seems to be that MTOM is not supported in .NET Core: https://github.com/dotnet/wcf/issues/1810
			// This code fails with this error:
			// The content type multipart/related; type="application/xop+xml"; boundary="uuid:3a65bca9-ef56-4bf3-8949-979637074058"; start="<root.message@cxf.apache.org>"; start-info="text/xml" of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 602 bytes of the response were: '
			// --uuid:3a65bca9-ef56-4bf3-8949-979637074058
			// Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
			// Content-Transfer-Encoding: binary
			// Content-ID: <root.message@cxf.apache.org>

			//	<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:uploadResponse xmlns:ns2="http://service.webload.efo.fec.gov/"><return>{"status":"PROCESSING","report_id":"","message":"Please check in few minutes for status update","submission_id":"EQRD230227548844","success":true}</return></ns2:uploadResponse></soap:Body></soap:Envelope>
			//	--uuid:3a65bca9-ef56-4bf3-8949-979637074058--'.
			var response = await webService.uploadAsync(JsonSerializer.Serialize(arg0), arg1);
			var rv = response.@return;
		}

		private static FecSubmissionDetails GetFecSubmissionDetails()
		{
			FecSubmissionDetails fecSubmissionDetails = new (
				CommitteeId: "C00363168",
				Password: "XXXXXXXXXX",
				ApiKey: "XXXXXXXXXXXXXXXXXXX",
				Email1: "",
				Email2: "",
				AgencyId: "VEND",
				AmendmentId: ""
			);

			return fecSubmissionDetails;
		}
	}
}
